sonar.projectKey=assistencia-tecnica-adm
sonar.projectName=Assistencia Tecnica ADM
sonar.projectVersion=0.1.0

sonar.sources=backend
sonar.sources.inclusions=**/*.py

sonar.exclusions=**/tests/**,**/__pycache__/**,**/*.pyc,**/frontend/**,**/node_modules/**,**/docs/**,**/data/**

sonar.language=py
sonar.scm.provider=git
sonar.sourceEncoding=UTF-8

sonar.tests=tests
sonar.test.inclusions=tests/**/*.py

sonar.python.coverage.reportPaths=coverage.xml
sonar.python.coveragePlugin=cobertura